"""Generate the course navigation data and check the AB-650 lab content.

Usage:
    python tools/check_labs.py          # run all checks (used by CI)
    python tools/check_labs.py --write  # regenerate _data/course.yml, then run all checks

The navigation data (_data/course.yml) is generated from the lab guides, so lab titles,
exercises, minutes, and file links have one source: the Markdown in Instructions/Labs.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
LABS = ROOT / "Instructions" / "Labs"
ALLFILES = ROOT / "Allfiles"
DATA = ROOT / "_data" / "course.yml"

LEARNING_PATHS = [
    {"number": 1, "folder": "LP1", "title": "Configure and manage Microsoft 365 tenants and workloads",
     "learn_url": "https://learn.microsoft.com/training/paths/configure-manage-microsoft-365-tenants-workloads/"},
    {"number": 2, "folder": "LP2", "title": "Govern and secure Microsoft 365 tenants and workloads",
     "learn_url": "https://learn.microsoft.com/training/paths/govern-secure-microsoft-365-tenants-workloads/"},
    {"number": 3, "folder": "LP3", "title": "Manage and secure Microsoft 365 AI services",
     "learn_url": "https://learn.microsoft.com/training/paths/manage-secure-microsoft-365-ai-services/"},
]
GETTING_STARTED = "Instructions/Labs/00-getting-started.md"
REQUIRED_LAB_FIELDS = ("title", "description", "duration", "level", "islab")

EXERCISE = re.compile(r"^## Exercise (\d+): (.+)$", re.M)
ESTIMATE = re.compile(r"^\*\*Estimated time:\*\* (\d+) minutes\.", re.M)
LINK = re.compile(r"!?\[[^\]]*\]\(([^)\s]+)\)")
FPATH = re.compile(r"F:\\([A-Za-z0-9]+)(?:\\([A-Za-z0-9._-]+\.[A-Za-z0-9]+))?")
FENCE = re.compile(r"^\s*```(\S*)")


def front_matter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---\n", 4)
    return yaml.safe_load(text[4:end]) or {}, text[end + 5:]


def lab_files() -> list[Path]:
    return sorted(p for p in LABS.glob("LP*/0*.md") if re.match(r"0\d-", p.name))


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def build_data() -> dict:
    paths = []
    for lp in LEARNING_PATHS:
        labs = []
        for path in lab_files():
            if path.parent.name != lp["folder"]:
                continue
            _, body = front_matter(path)
            headings = EXERCISE.findall(body)
            estimates = [int(m) for m in ESTIMATE.findall(body)]
            exercises = [{"title": title.strip(), "minutes": minutes}
                         for (_, title), minutes in zip(headings, estimates)]
            files, cases = [], []
            for target in LINK.findall(body):
                if target.startswith(("http", "#", "mailto:")):
                    continue
                resolved = (path.parent / target.split("#")[0]).resolve()
                if not resolved.is_file():
                    continue
                if ALLFILES in resolved.parents:
                    item = resolved.relative_to(ALLFILES).as_posix()
                    if item not in files:
                        files.append(item)
                elif resolved.suffix == ".md" and resolved.parent.name == "assets":
                    item = rel(resolved)
                    if item not in cases:
                        cases.append(item)
            labs.append({"number": int(path.name[:2]), "file": rel(path), "exercises": exercises,
                         "files": files, "sample_cases": cases})
        paths.append({key: lp[key] for key in ("number", "title", "learn_url")} | {"labs": labs})
    return {"getting_started": GETTING_STARTED, "learning_paths": paths}


def dump(data: dict) -> str:
    header = "# Generated by tools/check_labs.py --write from the lab guides. Don't edit by hand.\n"
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=200)


def check() -> list[str]:
    errors = []
    labs = lab_files()
    if not labs:
        errors.append("No lab guides found in Instructions/Labs/LP*/")
    for path in labs:
        meta, body = front_matter(path)
        lab = meta.get("lab") or {}
        for field in REQUIRED_LAB_FIELDS:
            if field not in lab:
                errors.append(f"{rel(path)}: front matter lab.{field} is missing")
        headings = EXERCISE.findall(body)
        estimates = [int(m) for m in ESTIMATE.findall(body)]
        if len(headings) != len(estimates):
            errors.append(f"{rel(path)}: {len(headings)} exercises but {len(estimates)} 'Estimated time' lines")
        if isinstance(lab.get("duration"), int) and estimates and sum(estimates) != lab["duration"]:
            errors.append(f"{rel(path)}: exercise minutes add up to {sum(estimates)}, but lab.duration is {lab['duration']}")
        if [int(n) for n, _ in headings] != list(range(1, len(headings) + 1)):
            errors.append(f"{rel(path)}: exercises aren't numbered 1..{len(headings)}")

    referenced = set()
    for path in sorted((ROOT / "Instructions").rglob("*.md")) + [ROOT / "index.md"]:
        text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if "<!--" in text:
            errors.append(f"{rel(path)}: contains an HTML comment; keep internal notes out of published lab files")
        inside = False
        for number, line in enumerate(text.splitlines(), 1):
            fence = FENCE.match(line)
            if fence:
                if not inside and not fence.group(1):
                    errors.append(f"{rel(path)}:{number}: code fence needs a language, such as text or powershell")
                inside = not inside
        for target in LINK.findall(text):
            if target.startswith(("http://", "https://", "#", "mailto:", "{{")):
                continue
            resolved = (path.parent / target.split("#")[0]).resolve()
            if not resolved.exists():
                errors.append(f"{rel(path)}: link target doesn't exist: {target}")
            elif ALLFILES in resolved.parents:
                referenced.add(resolved)
        for folder, name in FPATH.findall(text):
            target = ALLFILES / folder / name if name else ALLFILES / folder
            if not target.exists():
                errors.append(f"{rel(path)}: F:\\{folder}{chr(92) + name if name else ''} isn't in Allfiles")
            elif name:
                referenced.add(target.resolve())
        for folder in re.findall(r"\*\*AllFiles \(F:\)\*\* > \*\*([A-Za-z0-9]+)\*\*", text):
            if not (ALLFILES / folder).is_dir():
                errors.append(f"{rel(path)}: AllFiles folder {folder} doesn't exist")

    readme = (ALLFILES / "README.md").read_text(encoding="utf-8")
    for path in sorted(ALLFILES.rglob("*")):
        if path.is_file() and path.name != "README.md":
            if path.resolve() not in referenced and path.parent.name != "ClassActivities":
                errors.append(f"{rel(path)}: isn't used by any lab guide")
            if path.name not in readme:
                errors.append(f"{rel(path)}: isn't listed in Allfiles/README.md")

    if not (ROOT / GETTING_STARTED).is_file():
        errors.append(f"{GETTING_STARTED} is missing")
    expected = dump(build_data())
    if not DATA.is_file() or DATA.read_text(encoding="utf-8").replace("\r\n", "\n") != expected:
        errors.append("_data/course.yml is out of date. Run: python tools/check_labs.py --write")
    return errors


def main() -> int:
    if "--write" in sys.argv:
        DATA.parent.mkdir(exist_ok=True)
        DATA.write_text(dump(build_data()), encoding="utf-8", newline="\n")
        print(f"Wrote {rel(DATA)}")
    errors = check()
    for error in errors:
        print(f"ERROR: {error}")
    print(f"{len(lab_files())} labs checked, {len(errors)} problem(s) found.")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
